### ISSUE TITLE
No obvious way to manage the menu.

### ISSUE THREAD

**Issue by svein83** [jerone/menu-manager#6] opened 2018-06-30 14:01 UTC
As far as I can see, this is a menu-viewer, and not a menu-manager... If it is a manager, then how does one manage menus with it??

Either the functionality is missing, OR a document explaining how to use it is missing...

**Comment by jerone** [comment] 2018-07-02 08:40
Duplicate of https://github.com/jerone/menu-manager/issues/2

**Closed as completed by jerone** 2018-07-02 08:40 UTC
Labels: duplicate
